config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'rules' => 'static_pages#rules'
  get 'about' => 'static_pages#about'
  get 'goals' => 'static_pages#goals'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  resources :categories do
    resources :posts, only: [:new, :create]
  end

  resources :posts, except: [:new, :create] do
      resources :comments
  end

end

app/views/layouts/_sideabout.html.erb
<!-- Side Widget Well -->
<div class="well">
    <h4>My Gear</h4>
      <ul class="list-unstyled">
          <li>A $200 ASUS (yup, Windows) laptop</li>
          <li>Sublime Text 2</li>
          <li>No internet at home, which is where I work most often</li>
      </ul>
</div>

app/views/layouts/_sidecategories.html.erb
<!-- Blog Categories Well -->
<div class="well">
    <h4>All 52 Projects</h4>
    <div class="row">
        <ul class="list-unstyled">
            <% @categories.each do |category| %>
                <li class="col-lg-6"><%= link_to category.name, category_path(category[:id]) %></li>
            <% end %>
        </ul>
    </div>
    <!-- /.row -->
</div>


app/views/layouts/_sidegoals.html.erb
<!-- Side Widget Well -->
<div class="well">
    <h4>Goals This Week</h4>
    <ul class="list-unstyled">
      <li>The Wordpress Loop</li>
      <li>Create a mobile-responsive site</li>
      <%= link_to "The Full List", goals_path %>
    </ul>
</div>

app/views/layouts/_siderules.html.erb
<!-- Side Widget Well -->
<div class="well">
    <h4>The Rules</h4>
      <ul class="list-unstyled">
        <li>One website, web app, or project each week from Monday morning to Sunday midnight.</li><br>
        <li>All code open source and posted to <a href="https://github.com/AngieGreen">Github</a>.</li><br>
        <li>At least one blog post per project, sharing what I've learned.</li><br>
        <li>No refactoring of the code after the project's week is over.</li>
      </ul>
</div>

app/views/layouts/_sidesearch.html.erb
<!-- Blog Search Well -->
<div class="well">
    <h4>Search</h4>
    <div class="input-group">
        <input type="text" class="form-control">
        <span class="input-group-btn">
            <button class="btn btn-default" type="button">
                <span class="fa fa-fw fa-search"></span>
        </button>
        </span>
    </div>
    <!-- /.input-group -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="The 52 Apps Project: 52 Apps in 52 Weeks">
  <meta name="author" content="Angie Rae Green">

  <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
  <link href="../../assets/stylesheets/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="../../assets/stylesheets/freelancer.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lato|Great+Vibes|Inconsolata' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="http://www.angieraegreen.com/blog">52 Apps Project</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <%= link_to "About", about_path %>
                    </li>
                    <li>
                        <%= link_to "The Rules", rules_path %>
                    </li>
                    <li>
                        <%= link_to "All 52 Apps", categories_path %>
                    </li>
                    <li>
                        <%= link_to "Contact", href="http://www.angieraegreen.com/contact" %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>


    <div class="container">
      <%= yield %>
    </div>

     <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>52 Apps in 52 Weeks</h3>
                        <p>Learning to code the crazy way</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="https://www.facebook.com/angie.green.7524" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/u/0/+AngieGreenNOLA" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="https://twitter.com/angieraegreen" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/angiergreen" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                            </li>
                            <li>
                                <a href="https://github.com/AngieGreen" class="btn-social btn-outline"><i class="fa fa-fw fa-github"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Want more?</h3>
                        <p>My real portfolio is available at <a href="http://angieraegreen.com">www.angieraegreen.com</a></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="small">Copyright &copy; <%= Time.now.year %> <a href="http://angieraegreen.com">Angie Rae Green</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll visible-xs visible-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

        <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/freelancer.js"></script>

  </body>

</html>